/*********************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 *
 * Generated Date: 2/19/2020
 *********************************************************************************************/

#ifndef PNP_DEVICE
#define PNP_DEVICE

/* Standard includes. */
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C"
{
#endif

int pnp_device_initialize(const char* connectionString, const char* trustedCert);

void pnp_device_run();

void pnp_device_close();

#ifdef __cplusplus
}
#endif

#endif // PNP_DEVICE
